### ISSUE TITLE
Css insted sass

### ISSUE THREAD

**Issue by ghost** [Fraina/Material-Design-ColorPicker#5]
Can you give css version insted sass ?

**Comment by fraina** [comment]
This project is just a simple tool for picking color easier, it makes no difference with sass or hand-writing css. It also too complicate to write css comparing to sass, so I will not provide a css version of this project.

FYI, you can download a compiled css from https://github.com/Fraina/Material-Design-ColorPicker/blob/gh-pages/css/screen.css, but it's not suggested.

**Comment by ghost** [comment]
Thank you very much for screen.css file. Unfortunately I do not know how to work with sass and Compass. I use a WebStorm and I did not understand how to configure Compass. Among other things, I am not able work with sass or less - I do not know the syntax. In view of the foregoing, I had to ask you to give me the compiled stylesheet. Thank you again.
